export type Market='USA'|'CANADA'|'INDIA';export type Cap='SMALL'|'MID'|'LARGE';
export type Candidate={ticker:string;name:string;market:Market;exchange:string;cap:Cap;sector:string;price:string;change:number;score:number;signal:'ACCUMULATE'|'WATCH'|'AVOID';thesis:string;tags:string[];freshness:string};
export const candidates:Candidate[]=[
{ticker:'USIN',name:'Sample Industrial Services',market:'USA',exchange:'NYSE',cap:'MID',sector:'Industrials',price:'$42.18',change:1.42,score:86,signal:'ACCUMULATE',thesis:'Recurring maintenance demand, improving cash conversion, and a measurable contract catalyst.',tags:['Boring business','Contract catalyst'],freshness:'DEMO · 30M'},
{ticker:'USWT',name:'Sample Water Systems',market:'USA',exchange:'NASDAQ',cap:'SMALL',sector:'Utilities',price:'$18.64',change:.76,score:81,signal:'WATCH',thesis:'Essential infrastructure exposure with backlog growth; valuation still requires discipline.',tags:['Essential','Underfollowed'],freshness:'DEMO · 30M'},
{ticker:'CAFS',name:'Sample Facility Services',market:'CANADA',exchange:'TSX',cap:'SMALL',sector:'Commercial services',price:'C$27.35',change:1.08,score:83,signal:'ACCUMULATE',thesis:'Route density and recurring contracts support margins while institutional ownership remains modest.',tags:['Boring business','Low coverage'],freshness:'DEMO · 30M'},
{ticker:'CARG',name:'Sample Rail Logistics',market:'CANADA',exchange:'TSX',cap:'MID',sector:'Transportation',price:'C$54.90',change:-.31,score:75,signal:'WATCH',thesis:'Durable network economics, but the entry setup awaits improving relative strength.',tags:['Essential','Dividend'],freshness:'DEMO · 30M'},
{ticker:'INPX',name:'Sample Precision Components',market:'INDIA',exchange:'NSE',cap:'MID',sector:'Manufacturing',price:'₹1,284.60',change:2.14,score:85,signal:'ACCUMULATE',thesis:'Import substitution, export orders, and capacity utilization create an earnings runway.',tags:['Make in India','Order book'],freshness:'DEMO · 30M'},
{ticker:'INPO',name:'Sample Port Services',market:'INDIA',exchange:'BSE',cap:'SMALL',sector:'Logistics',price:'₹418.25',change:-.62,score:78,signal:'WATCH',thesis:'Port-linked cash flows and freight growth are attractive; governance checks remain open.',tags:['Core infrastructure','Underfollowed'],freshness:'DEMO · 30M'}];
export const flows=[{region:'USA',label:'13F institutional positioning',value:'Quarterly disclosure',status:'FILING',note:'Can be filed up to 45 days after quarter-end.'},{region:'CANADA',label:'Insider disclosure pulse',value:'Event-driven filing',status:'FILING',note:'Not a live view of every investor transaction.'},{region:'INDIA',label:'FII / DII aggregate activity',value:'Published market total',status:'DELAYED',note:'Aggregate activity, not investor-by-investor intent.'},{region:'GLOBAL',label:'ETF and fund allocation pressure',value:'Daily estimate',status:'ESTIMATE',note:'Direction indicator; provider methodology required.'}];
export const intelligence=[{region:'GLOBAL',type:'POLICY',headline:'Sample policy catalyst enters the research queue',detail:'Production will link primary documents, affected sectors, named companies, and confidence.'},{region:'INDIA',type:'CONTRACT',headline:'Sample infrastructure order requires verification',detail:'Contract value, execution period, customer concentration, and margin quality must be checked.'},{region:'NORTH AMERICA',type:'EARNINGS',headline:'Sample margin inflection detected',detail:'Production will separate sustainable operating improvement from one-time items.'}];
export const samplePositions=[['DEMO-CA','Sample Canadian holding','C$46.24','+2.84%','28%',true],['DEMO-US','Sample U.S. holding','$24.18','-1.12%','19%',false],['DEMO-IN','Sample Indian holding','₹613.20','+4.07%','17%',true],['CASH','Reserved buying power','$500.00','0.00%','23%',true]] as const;
